import { z } from "zod";

export const TruestackKycSessionRowSchema = z.object({
  id: z.string(),
  externalSessionId: z.string(),
  directorId: z.string().nullable(),
  onboardingUrl: z.string(),
  expiresAt: z.string().nullable(),
  status: z.string(),
  result: z.string().nullable(),
  rejectMessage: z.string().nullable(),
  lastWebhookAt: z.string().nullable(),
  createdAt: z.string().nullable().optional(),
  updatedAt: z.string(),
});

export const TruestackKycStatusDataSchema = z.object({
  borrowerType: z.string(),
  sessions: z.array(TruestackKycSessionRowSchema),
  latest: TruestackKycSessionRowSchema.nullable(),
});

export const BorrowerDocumentSchema = z.object({
  id: z.string(),
  filename: z.string(),
  originalName: z.string(),
  mimeType: z.string(),
  size: z.number(),
  path: z.string(),
  category: z.string(),
  uploadedAt: z.string(),
});

export const BorrowerDirectorSchema = z.object({
  id: z.string(),
  name: z.string(),
  icNumber: z.string(),
  position: z.string().nullable(),
  order: z.number(),
  isAuthorizedRepresentative: z.boolean().optional(),
});

export const BorrowerDetailSchema = z.object({
  id: z.string(),
  borrowerType: z.string(),
  name: z.string(),
  icNumber: z.string(),
  documentType: z.string(),
  documentVerified: z.boolean(),
  verificationStatus: z.string().nullable().optional(),
  trueIdentityStatus: z.string().nullable().optional(),
  trueIdentityResult: z.string().nullable().optional(),
  phone: z.string().nullable(),
  email: z.string().nullable(),
  address: z.string().nullable(),
  addressLine1: z.string().nullable(),
  addressLine2: z.string().nullable(),
  city: z.string().nullable(),
  state: z.string().nullable(),
  postcode: z.string().nullable(),
  country: z.string().nullable(),
  dateOfBirth: z.string().nullable(),
  gender: z.string().nullable(),
  race: z.string().nullable(),
  educationLevel: z.string().nullable(),
  occupation: z.string().nullable(),
  employmentStatus: z.string().nullable(),
  bankName: z.string().nullable(),
  bankNameOther: z.string().nullable(),
  bankAccountNo: z.string().nullable(),
  emergencyContactName: z.string().nullable(),
  emergencyContactPhone: z.string().nullable(),
  emergencyContactRelationship: z.string().nullable(),
  monthlyIncome: z.union([z.string(), z.number(), z.null()]),
  instagram: z.string().nullable(),
  tiktok: z.string().nullable(),
  facebook: z.string().nullable(),
  linkedin: z.string().nullable(),
  xTwitter: z.string().nullable(),
  companyName: z.string().nullable(),
  ssmRegistrationNo: z.string().nullable(),
  businessAddress: z.string().nullable(),
  bumiStatus: z.string().nullable(),
  authorizedRepName: z.string().nullable(),
  authorizedRepIc: z.string().nullable(),
  companyPhone: z.string().nullable(),
  companyEmail: z.string().nullable(),
  natureOfBusiness: z.string().nullable(),
  dateOfIncorporation: z.string().nullable(),
  paidUpCapital: z.union([z.string(), z.number(), z.null()]),
  numberOfEmployees: z.number().nullable(),
  directors: z.array(BorrowerDirectorSchema),
  documents: z.array(BorrowerDocumentSchema),
});

export const UpdateBorrowerPayloadSchema = z.object({
  name: z.string().optional(),
  icNumber: z.string().optional(),
  documentType: z.string().optional(),
  phone: z.string().optional(),
  email: z.string().optional(),
  addressLine1: z.string().optional(),
  addressLine2: z.string().optional(),
  city: z.string().optional(),
  state: z.string().optional(),
  postcode: z.string().optional(),
  country: z.string().optional(),
  dateOfBirth: z.string().optional(),
  gender: z.string().optional(),
  race: z.string().optional(),
  educationLevel: z.string().optional(),
  occupation: z.string().optional(),
  employmentStatus: z.string().optional(),
  bankName: z.string().optional(),
  bankNameOther: z.string().optional(),
  bankAccountNo: z.string().optional(),
  monthlyIncome: z.number().nullable().optional(),
  emergencyContactName: z.string().optional(),
  emergencyContactPhone: z.string().optional(),
  emergencyContactRelationship: z.string().optional(),
  instagram: z.string().optional(),
  tiktok: z.string().optional(),
  facebook: z.string().optional(),
  linkedin: z.string().optional(),
  xTwitter: z.string().optional(),
  companyName: z.string().optional(),
  ssmRegistrationNo: z.string().optional(),
  businessAddress: z.string().optional(),
  authorizedRepName: z.string().optional(),
  authorizedRepIc: z.string().optional(),
  companyPhone: z.string().optional(),
  companyEmail: z.string().optional(),
  natureOfBusiness: z.string().optional(),
  dateOfIncorporation: z.string().optional(),
  paidUpCapital: z.number().nullable().optional(),
  numberOfEmployees: z.number().nullable().optional(),
  bumiStatus: z.string().optional(),
  directors: z.array(z.object({
    name: z.string(),
    icNumber: z.string(),
    position: z.string().optional(),
    id: z.string().optional(),
    isAuthorizedRepresentative: z.boolean().optional(),
  })).optional(),
});
