#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# LOCATION @/opt/mtsa/ #
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

#API
#production or pilot 
api.stage=pilot
project.name=ANDAS CAPITAL AP PKI Pilot

project.account.name=DocSigningBasicPilot
project.account.type=AP

#leave blank=not specified
project.cert_corp_company=
project.cert_org_unit=

workdir.path=/opt/mtsa
aes.key=J7B{m.y2E9vwL2w<
aes.iv=Pk6D%D#{QzU#3?RJ
#in KB
upload.limit=2048000

#TSA
#TSA : TSA-URL,TSA-USER,TSA-PASSWD|TSA1-URL,TSA1-USER,TSA1-PASSWD|TSA2-URL,TSA2-USER,TSA2-PASSWD
#set -1 if no user/passwd needed
tsa.info=https://digitalid.msctrustgate.com/adss/tsa,-1,-1|https://pki.msctrustgate.com/tsa,-1,-1

#MTSS WSDL
mtss.ws.ds=https://digitalid.msctrustgate.com/MyTrustSignerServicePilot/digitalSigningHash/digitalSigning?wsdl
mtss.ws.otpsms=https://digitalid.msctrustgate.com/MyTrustSignerServicePilot/otpService/otpService?wsdl
mtss.ws.projectprofile=https://digitalid.msctrustgate.com/MyTrustSignerServicePilot/getProjectProfile/getProjectProfile?wsdl
mtss.ws.certinfo=https://digitalid.msctrustgate.com/MyTrustSignerServicePilot/getCertInfo/getCertInfo?wsdl
mtss.ws.clc=https://digitalid.msctrustgate.com/MyTrustSignerServicePilot/CLCService/CLCServiceWS?wsdl
mtss.ws.renew.enrol=https://digitalid.msctrustgate.com/MyTrustSignerServicePilot/renewEnrol/renewEnrol?wsdl
mtss.ws.resetpin=https://digitalid.msctrustgate.com/MyTrustSignerServicePilot/resetPIN/resetPIN?wsdl
mtss.ws.hcauth=https://digitalid.msctrustgate.com/MyTrustSignerServicePilot/HCauthService/HCauthService?wsdl
mtss.ws.ekyc=https://digitalid.msctrustgate.com/MyTrustSignerServicePilot/ekycV3/ekycService/ekycService?Wsdl
mtss.ws.report=https://digitalid.msctrustgate.com/MyTrustSignerServicePilot/ReportingWS/GetReport?wsdl
mtss.ws.clcv2=https://digitalid.msctrustgate.com/MyTrustSignerServicePilot/CLCServiceV2/CLCServiceV2?wsdl
mtss.ws.txlog=https://digitalid.msctrustgate.com/MyTrustSignerServicePilot/updateTXlogger/updateTXlogger?wsdl
mtss.ws.verifycertpin=https://digitalid.msctrustgate.com/MyTrustSignerServicePilot/verifyCertPIN/verifyCertPIN?wsdl
mtss.ws.ekyc.ctos.url=https://digitalid.msctrustgate.com/MyTrustSignerServicePilot/CtosAPIRequest?wsdl
mtss.ws.clcv3=https://digitalid.msctrustgate.com/MyTrustSignerServicePilot/CLCServiceV3/CLCServiceV3?wsdl
mtss.ws.verifyclientuser=https://digitalid.msctrustgate.com/MyTrustSignerServicePilot/verifyClientUser-nonRAv2/verifyClientUser?wsdl
mtss.ws.prepaidsvc=https://digitalid.msctrustgate.com/MyTrustSignerServicePilot/mtssPrepaid/mtssPrepaid?wsdl
mtss.ws.verifyUserDataSuci=https://digitalid.msctrustgate.com/MyTrustSignerServicePilot/verifyUserDataSuci/verifyUserDataSuci?wsdl
mtss.ws.certinfoBySDN=https://digitalid.msctrustgate.com/MyTrustSignerServicePilot/getCertInfoBySubjectDN/getCertInfo?wsdl
mtss.ws.projectAuth=https://digitalid.msctrustgate.com/MyTrustSignerServicePilot/ProjectAuthService/ProjectAuthService?wsdl

#MTIDA URL
mtida.activation.url=https://www.msctrustgate.com/pilot/mytrustid/client/activation?token=
mtida.svc.url=https://www.msctrustgate.com/pilot/mytrustid/generic?q=
mtida.svc.request=request
mtida.svc.checkstatus=checkStatus
mtida.svc.getactivation=getActivation
mtida.svc.document=document
mtida.svc.sendactivation=sendActivation
mtida.svc.revoke=revoke
mtida.svc.renewal=renewal
mtida.svc.autorenewal=autorenewal
mtida.svc.getrequest=getRequest
mtida.svc.unsetap=unsetAP

#MTIDA AUTH
mtida.user=ej1sbIsHcadB9i2GFd0X0w==
mtida.pass=Olnm8JSYw5XfzzSxC5M+Uw==

#MTSS AUTH
mtss.ws.user=P/6MFoy2UqtQxf0scuylig==
mtss.ws.pass=09h/m4umGL/GaAmkUKS9D/XNJvj4l9zeLaARROPFZj4=
mtss.ws.projectkey=4APKP8bOv7mr/y1BF4o5AQ==

#ORGCERT
mtss.ws.orgcert.account=
mtss.ws.orgcert.cn=

#-1 if not applicable
mtss.ws.orgcert.user=-1
mtss.ws.orgcert.pass=-1
mtss.ws.orgcert.projectkey=-1

#MTSS EKCY
mtss.ws.ekyc.user=mVTQbt4wD2l317VaeXfmDw==
mtss.ws.ekyc.pass=r+DdAWsiBPBe5WgNpidZKA==

#MTSS EKYCv4
mtss.ws.ekyc.v4.url=https://digitalid.msctrustgate.com/MyTrustSignerServicePilot/ekycV4/ekycService/ekycService?Wsdl
mtss.ws.ekyc.v4.accountname=andas-capital

#MTSS EKYCv6
mtss.ws.ekyc.v6.url=https://digitalid.msctrustgate.com/MyTrustSignerServicePilot/ekycV6/ekycService/ekycService?Wsdl
mtss.ws.ekyc.v6.accountname=andas-capital

#internal
mtss.ws.internal.user=Bhis60+OkXZNPzj/y8fxdg==
mtss.ws.internal.pass=r+DdAWsiBPBe5WgNpidZKA==

#QRCode
mtss.service.qr.verifier=https://digitalid.msctrustgate.com/MyTrustSignerServicePilot/QRVerifier/VerifyQRCode
qr.height=1
qr.width=1

#SIG TEMPLATE
dsig.template1=Digitally signed by\n<FULL_NAME>\n<USER_ID>\n<TS>\n<INFO1>
#0=aspervalue, 1=ALLCAP, 2=FirstLetterCap
dsig.template.text=0
#0=autofit
dsig.template.fontsize=10

#DS display render: G/GAD/NAD/D
ds.render=GAD

#auditlog flag
auditlog=1

#ekyc flag
ekyc.facial.flag=1

#multi ca
multica.flag=1
multica.file.infotype=andas-capital-type-info.pilot-v1.0.xml

#default project info for request
project.org.name=Andas Capital Sdn. Bhd.
#Address|City|Postcode|State|Country
project.org.fulladdress=No. 13, 1st Floor, Persiaran Mahsuri 1/3, Sunway Tunas|Bayan Lepas|11900|Penang|MY

#roaming|roaming_sks (aatl)
cert.type=roaming
