#length validation mapping
enrol.userid=12
enrol.idtype=1
enrol.fullname=100
enrol.nationality=2
enrol.email=50
enrol.mobileno=15
enrol.address.line=200
enrol.address.city=50
enrol.address.state=50
enrol.address.country=2
enrol.orginfo.name=50
enrol.orginfo.designation=50
enrol.orginfo.address=200
enrol.orginfo.city=50
enrol.orginfo.postcode=5
enrol.orginfo.state=50
enrol.orginfo.country=2
enrol.orginfo.regisno=20
enrol.orginfo.phoneno=15
enrol.orginfo.faxno=15
enrol.idfrontimage=-1
enrol.idbackimage=-1
enrol.cert.pin=8

ta.authdata.status=100
ta.authdata.datetime=yyyy-MM-dd HH:mm:ss
ta.authdata.verifier=100

otp.userid=12
otp.mobileno=15
otp.email=50

sign.userid=12
sign.fullname=100
#8=pin, 6=otp
sign.authfactor=8
sign.pdfrefid=50
sign.info.pageno=1
sign.info.x1=3
sign.info.x2=3
sign.info.y1=3
sign.info.y2=3

revoke.userid=12
revoke.certsno=50
revoke.reason=100
revoke.idtype=1

getcert.userid=12

verify.pdfstr=-1

ap.verifydata.status=100
ap.verifydata.datetime=yyyy-MM-dd HH:mm:ss
ap.verifydata.verifier=100
ap.verifydata.method=100

#resetpin
reset.cert.pin=8
reset.userid=12
reset.certsno=50