/**
 * Initial form data for borrower onboarding (individual & corporate).
 */

import { DEFAULT_COUNTRY_CODE } from "./address-options";
import type { IndividualFormData, CorporateFormData } from "./borrower-form-types";

export const initialIndividualFormData: IndividualFormData = {
  name: "",
  icNumber: "",
  documentType: "IC",
  phone: "",
  email: "",
  addressLine1: "",
  addressLine2: "",
  city: "",
  state: "",
  postcode: "",
  country: DEFAULT_COUNTRY_CODE,
  dateOfBirth: "",
  gender: "",
  race: "",
  educationLevel: "",
  occupation: "",
  employmentStatus: "",
  bankName: "",
  bankNameOther: "",
  bankAccountNo: "",
  emergencyContactName: "",
  emergencyContactPhone: "",
  emergencyContactRelationship: "",
  monthlyIncome: "",
  instagram: "",
  tiktok: "",
  facebook: "",
  linkedin: "",
  xTwitter: "",
};

export const initialCorporateFormData: CorporateFormData = {
  name: "",
  icNumber: "",
  phone: "",
  email: "",
  companyName: "",
  ssmRegistrationNo: "",
  addressLine1: "",
  addressLine2: "",
  city: "",
  state: "",
  postcode: "",
  country: DEFAULT_COUNTRY_CODE,
  bumiStatus: "",
  authorizedRepName: "",
  authorizedRepIc: "",
  companyPhone: "",
  companyEmail: "",
  natureOfBusiness: "",
  dateOfIncorporation: "",
  paidUpCapital: "",
  numberOfEmployees: "",
  bankName: "",
  bankNameOther: "",
  bankAccountNo: "",
  instagram: "",
  tiktok: "",
  facebook: "",
  linkedin: "",
  xTwitter: "",
  directors: [{ name: "", icNumber: "", position: "", isAuthorizedRepresentative: true }],
};
